const { RefactorSession } = require('shift-refactor');
const { parseScript } = require('shift-parser');
const Shift = require('shift-ast');
const unraw = require('unraw');

const fileContents = require('fs').readFileSync('./giveaway_spam.js', 'utf8');

const tree = parseScript(fileContents);

const refactor = new RefactorSession(tree);

/*
String deobfuscation functions, copied from giveaway_spam.js
*/
var deobfuscationFunctionName = "b";
var a = [
  'ExPhsmk5WPP7WOVcISkYs8o7W5K=',
  'WO7dG0LlwW==',
  'WRFcGvfZWQ1UWQ16W6pcG8ojW5hcScldN8k7gur7xGPiyCkyW6ldJqm=',
  'WPVcRKP/WRS=',
  'nmooWOdcQq==',
  'W7W4ca==',
  'W6TOWPnM',
  'ALTdhmksFCkBWO8=',
  'w8kbW59Esri=',
  'F0JdGNucWPmB',
  'WPJcNHKf',
  'z1FcNSknAsnjW5ddIwe/emkpya==',
  'WOhcSejZWRDfWRK=',
  'iSkmWO/dJv8=',
  'W4/dIGSssYxdHKFcJq==',
  'wL5FgmkoqCkGWQ8M',
  'W5RdSmkFW6RdRCoK',
  'W7DzWQCOWOi6',
  'W6m8g8o0wvtcLq==',
  'sCotWPDE',
  'W4ujW7rZW4e=',
  'WRDUW4ldOSom',
  'WPtcV8kh',
  'W7StySk0WOpcRJCS',
  'yqFdKSoYya==',
  'lIyfn25HC8oFW4K=',
  'WQG+WRj/cSkHrCojWO8=',
  'W4LVWQLWca==',
  'r8kmW4futrG=',
  'W6iPb8oXta==',
  'n8oRnmodW6W=',
  'WRGFW7mPW5Py',
  'n8oUWQVdOSk/WP7cKSoMoSoWACoYW5ZdMaFdQHJcTZ7cL8knW7qOvY8Obuv4W6rlxgVcN8khWQtcNGmlha==',
  'WOH/W5JdQSoxomoVDCogWO4=',
  'WQSyFxZdHuPbDmopuSkSW7T2W7RdTJyTbmoEW5W6',
  'E8kdW4TAxHu=',
  'dbNdJWXJC31EW6e=',
  'bCouW4f0W6hcLCkoWQ8=',
  'vbSrga==',
  'ACkfoXmFWQtcLa==',
  'W5ddVq8fp8orW7y3',
  'W4hcJKHncq==',
  'j8k/WRhcRgtcLa==',
  'WPKOWPRcVCko',
  'qCkmW4LEvdpdVW==',
  'WP1jiSk+',
  's1RcMK0sjsGh',
  'W4NdKrSsqsldTa==',
  'W4eZW74Vqmk/rq==',
  'hduAgum=',
  'WPFdNKzr',
  'W4/dHSkYFSodWOZcK8keW7pdTs8Oiu8=',
  'xwnfrCkI',
  'sSobW6f8',
  'Df3cUCk8DY9kW5i=',
  'W4ldP8kzW6ddTCoK',
  'xhznrCkKWQLNW4BcU8kZsG==',
  'W7/dJbme',
  'rLGelCkgxSkPWOq=',
  'WPC6cYXVWOxdJ8kdW5nMW5W=',
  'WPaWW5ji',
  'W6eDW6VcKmkLAW==',
  'WOSWgIbYWP/dK8ke',
  'gfVcK0qt',
  'W4LOWQjW',
  'WR/cJSkSrCoR',
  'zKu+pCkrwCkZ',
  'W6H4W4xdJ8k9',
  'W43dP8keW4ldSCo1WQBdKcycsSo7vv4=',
  'DuH9tCkKWOPTW5/cH8kh',
  'AvZcJSkTFqLc',
  'W4fwWQi=',
  'k8osW4RcGWddLIldOG==',
  'W61QmSkEWOOsW4ZcImoN',
  'EeFdHwKb',
  'W6SVW7mfAW==',
  'WOSHW5m9W6bjWOldPSkpW43dONRdTW==',
  'WRL0W47dTCoriSo4pmoRWPlcImoYx8kijG==',
  'EeddHMK=',
  'yqddNSoY',
  'W6TmWQKSWOi=',
  'CrdcMJqmWPC=',
  'WQejr1JdTgv2wCoMyCkBW6PbW5BdLGaknCodW70y',
  'W6e4gCo5vuq=',
  'cJ8okM93',
  'y1pcHSkKvs5fW5VdK3Oq',
  'W7hcGf1rx1NcMmkiaq==',
  'W484W64AwCkcqLyfW5HNAW==',
  'eGBdVH9axxW=',
  'W5NdSSkCW67dQq==',
  'w8kxW49iwa4=',
  'WPKPWP3cVCoB',
  'p2ZcGNpcKv3cMCkZWRNdICkibhCxA08I',
  'W7/dHb8oha==',
  'nCo7W63dUt8=',
  'jJxdJGXlyN1cW4RcOrJcImo2FrNcImothW==',
  'WPNcPYe+',
  'W6H4W4BdJ8oP',
  'WR8iW6yZlSo6W4BdIg4=',
  'WOiKW6iIoCoT',
  'WPaOAwZdIKTDAq==',
  'W6TBW7ebAIZdNSonWQjxp8kukx5NW44r',
  'amklW5hcQ8k2',
  'zmklW4nova==',
  'd8oli8kmWO3cUhLLgfCevmkkW5S=',
  'W7K+WPNcGCoJAmoEWQLL',
  'WObwhSk1z0lcNWG=',
  'l8o3eCozW5VcUgZcMZ0bWP/dL3FdMLe=',
  'sSoaW6f8',
  'W7VcG8oW',
  'WQq3cY5RWPm=',
  'd8okjmkmW4G=',
  'qI7cUIa2WOzqW4iDbCosWPJcOq==',
  'quqlWPSd',
  'W68DW6y=',
  'WPv3mcG=',
  'iCkjWPNcVG==',
  'omo1WQhdPmkZWRJcMW==',
  'WRWFW7qPW4ze',
  'W4q4W7qTtmky',
  'iSoVWQtdOSkG',
  'W47dSmkzW7hdUmoI',
  'uWvIy8kr',
  'W6b3WP90WRaAha==',
  'pWpdMbTeE2a=',
  'c8kqWQ3cT2dcNxxcNItdVutdUwKmDW==',
  'W7y8h8oDvflcNCorW4flWP/cK33dUq==',
  'dZShau/dOW==',
  'W5tdGSkTvmoAWOVcTSkB',
  'vX5u',
  'WPjmi8k5zLNcKWpcHmoFW4T4WO1np23cH8oiWRyUzmkJWPyJC04hWRlcSZfaCMST',
  'aYeCd1tdJSkXBSkg',
  'WPXLWP0r',
  'gCoAW6fpW6tcKSkWWRRdUhCiWQ/dTW8=',
  'i8kcWOtcQbLxW6C=',
  'W7JcGeDxwxJcO8kRBCktuCk4hMpcVfZcQrdcOCoRWRVcTGVcKSoNjNZcTCksieNcUmk8WPnYW5/dNSo3sa==',
  'AebjFSoDfSkhW694WOKcWRdcRG==',
  'w8ksW4fswa==',
  'W6m8W7mLsW==',
  'W6eRbmo8tvtcHmoNW5PD',
  'h2ZcKNpcM3ZcMG==',
  'W4DTW7e=',
  'WPmIFLZdI0TEEmoxq8kTW6z8W43dPtGteCoSW58=',
  'emonW7nPW7/cQ8kjWQZdO28=',
  'WPxdG0nksW==',
  'oCkCWOZcPbu=',
  'nCo8W6FdUwO=',
  'jmkJWQVcPgBcG0C=',
  'WR1TWOynbW==',
  'WOZdPgzHyq==',
  'EepdIwm=',
  'ACoAzLSv',
  'mmkSW7/dPa==',
  'qNjhs8kJWOXVW47cQq==',
  'W4NdHSk3wmotWOpcT8kzW64=',
  'W6npWR3dNmkH',
  'W4jkWQWGWP4=',
  'W6uXymobWPq8W4y=',
  'uWjNy8karCkYWOy=',
  'WPRcLCkGW5ldHh1kF00Ah0ddI8kt',
  'W4zxWRrqWP0NiCkAetSfk8oiW4pdRSkgnSo1fmowvmobWQy=',
  'xXZcGtycWOXE',
  'WRflWQL0WOm=',
  'W61SpSob',
  'WRqiW60RW5bZWPBdVCkk',
  'aSoEW7XK',
  'eSkHWQZcHrvSW7hcLutcKCo1W6X5iq==',
  'WP8iW7WSoa==',
  'WO8+WRv3da==',
  'ktapdW==',
  'btOmd17dICkd',
  'W6noWRBdNmo1',
  'WP1xkCk/AN/cMG==',
  'xhzzqmk3WO5T',
  'W5pdJXmEtq==',
  'b8kwCCotWOdcMxS=',
  'txjsWO0BzZG=',
  'WPf0W47dOSogbmo6',
  'emkiWQq6W7y=',
  'W5uWWQbj',
  'rKrgga==',
  'W4WfW7eA',
  'jCkRySkA',
  'WPJcNX0fvG==',
  'W6i+CSonWOSsW5tcLmoW',
  'WONdRbqSW78=',
  'W75io8kK',
  'W4BcKSo7va==',
  'WQ0qWO8=',
  'uWvHyW==',
  'W5ddGSkJvCogWOVcTCktW64=',
  'zL3cMmknzcvm',
  'r3nIWOCmrdZdOCorwMPzW7nq',
  'emkjWQm6WQi=',
  'WQaOW7ndsKVcHCo2p8owqfqwW7eHW4RcJ8oRW6xcJeddUsf1WQi=',
  'WP9/W57dHSokp8oUDColWPxcK8oG',
  'W44VW7CJvG==',
  'W4ryWQnfWOaAna==',
  'W4ulW7zZ',
  'eSokWORdUmkN',
  'quidWPTw',
  'ed8klhu=',
  'W580W7q=',
  'hJeybKFdPCka',
  'W70QyCowWPu=',
  'WPa1W5bctW==',
  'W7KTAa==',
  'ymkFmG0=',
  'qSkcWRePWPnx',
  'xuPymSklz8kKWPafW5SKWOSioW==',
  'W4rgWQze',
  'aN5sF2q=',
  'WOqoW4nHy3O=',
  'W5iXgCo3vvi=',
  'WQ/cSuLXWQnVW79AW7VcHq==',
  'quqoWPS=',
  'W6SZW5y=',
  'WQmkW7yNW4y=',
  'WR3dICo8hSo6W6hcOCkrW7VcICoHv2S=',
  'atSmdW==',
  'oZ0gdKNdSCkwa8kAyCo7gt0=',
  'qwzDsCkKWQvCW6BcLG==',
  'W4VcS8oaWR3cRq==',
  'oCkrE8osWPFcOw4GlLyfx8kl',
  'WR/cICkOrCoR',
  'WOaeW5vWBG==',
  'yqBdNmoY',
  'A8kkpaKvWPi=',
  'WOmIAh3dLuDfEmol',
  'WPv1ospcLW==',
  'aSoEW7nYW7dcLa==',
  'W7WTA8oqWOmhW5NcI8oN',
  'c8kayCotWORcUhXS',
  'AgfgqCo2WO5NW4tcSCkZqCoMWOBcLa==',
  'WR0MW4y=',
  'WPRcU1z6WQ5PWRO=',
  'W6S6CmoHWOawW43cNSoSW4VdUmkOjLBdNSospSopaSoOWPXg',
  'nH7dGHTq',
  'WPDrp8k1F1xdKqJdNmoAW5TZWOXDEcRcNCkCWRK=',
  'AbmlACom',
  'cq/dMbnlz2TzW7RcUGu=',
  'W4pdRmkuW6ldPCoFWQ0=',
  'WPunF8oGDW==',
  'W5NdOCkcW6ldUmo+',
  'W64tW6i=',
  'gSkxrSocWORcV3nN',
  'srLEW4qEnSoa',
  'rSk9fIu5WOZdKcm+WQNdQCocWRxcMG9xeSka',
  'WOCKEhZdGKa=',
  'aSkrE8odWOa=',
  'pSoUWRhdPmk5WR/cQCofvG==',
  'WRmmW6ecp8o8W4FdINv1W7Td',
  'W5FdHSkL',
  'WP4dW5vHFLVcHW==',
  'W5G8W6GRvCkd',
  'lSoKW7r4W7FcJSkjWR7dSNuYWRJdTrFdL1G+W6iu',
  'WPX1W4NdSSotlSoYAmoSWOZcGSoOsCkdia==',
  'iSkpWONdJv8=',
  'W55gWQTjWOW=',
  'fq/dHbLwFa==',
  'fcyi',
  'nCo4W6tdSG==',
  'WOe0B2VdPKLwC8on',
  'W5STW7yJta==',
  'C1KZk8kBxSkJ',
  'oSkjWPlcOaHRW7lcRK7cJSoZ',
  'WPzzWOm+nG==',
  'WPTklSkQzW==',
  'zununmoCgmkqWQDT',
  'svZcNSkTDYHbW4hcH1afgCkQA8oukdO=',
  'd8o6mCofW6S=',
  'bw3cG2tcGfy=',
  'WOmcW6jWDh3cJ8o0',
  'xevpgmkerSks',
  'W4bxWQq=',
  'aN5EFZa=',
  'nmoyW5VcKai=',
  'W41wWQuSWOGCFG==',
  'W7yszCkKWPBcHd8=',
  'W6eWW7STuCkEqK8jW4nSorhcUeZdGN7cJmkWvSovW4ZdPmou',
  'WQymW6uVkSoRW5a=',
  'eSoZWRFdRSkMWPi=',
  'd8oljmkm',
  'W47dICkLvmomWQ3cPq==',
  'W5S2ASoaWOmeW5pdM8osW5FdPmkeoG==',
  'WRKuW74RW4PJWPi=',
  'zrnDW6a=',
  'uhnLWPWrqtddPW==',
  'W5u9WQ8w',
  'WQ7dMSoRdmoR',
  'B2nzqmkZ',
  'WPLLWPS3ccRdR33dL8oCtM90zG==',
  'EKDjimoafSkzWOT6',
  'qKFcJmkUydq=',
  'W7KSyCowWQ0uW4xcLCo2',
  'jSkfWO7cUbK=',
  'W57dRCkJW7pdR8o5WQxdKG==',
  'dwzFuem=',
  'W44JWPNcKSoGECkhWPbUWOW=',
  'pCkHWRRcPNFcOLi=',
  'WP9/W57dGSoslSoXECohWPtcLmohvCkUomopl8o+p8oNWOBdJa==',
  'W4nTW7ehAW==',
  'wSkhW51xtr/dVa==',
  'BvpcNSkRBq==',
  'nCo6W6ZdUq==',
  'qSoqW4bEaXhdSmo6WPm=',
  'WRC6WRj8',
  'DGxcLJ0=',
  'W7xdVf81sWldPxNcPdG=',
  'W6noWR/cGW==',
  'W4nHW7CxCtpdJCoAWO8=',
  'WRm2WRHSfW==',
  'rLVcMmkTyYLC',
  'WQBdTvPAuCoVWQxcKvpcPKvcW6ipkmkMngDgW6LmW7K0',
  'iSo4WRFdPmkUWPK=',
  'WRydW5v2Ax3cHq==',
  'nwRcHhNcJLy=',
  'm8ovW5JcMrRdMci=',
  'WQVcTLr5WQjV',
  'rLGBnSkduSk1WQddV8osWOa=',
  'WONdRruS',
  'WRBdMKHnuG==',
  'WOu5WROmW4bdWOpdUSkbW5O=',
  'acaGn2b/ECo9W5tdUa==',
  'WOtcV0HXWRPRWRH2W6y=',
  'W7G3d8o9qhJcLG==',
  'ACoEzve=',
  'WPNcUGCVDSoLWRj5',
  'qCkmESozWPtcThXYuu4gumknW73cNmoyWQhdMeDXWPz6sSohW5O=',
  'AqFcNcClWPDFW50t',
  'D31BWPSwrJNdGSorC29lW7Th',
  'W6H5W4tdJ8oP',
  'W6qTWPu=',
  'fCkBWPFdO1VcIfFcMIBdHKhdU2SxyCkT',
  'WOzUt3S3',
  'i8kQWRZcP33cHelcLZO=',
  'W6a8WPFcKq==',
  'W4LUWQPWxSkrt0Gf',
  'WPbwimkBz0tcKWddHCoAW5DYWPf3EcRdK8obW7KzzSkNWPa=',
  'W5u1WQbjmW==',
  'AbepACom',
  'BWDFW5mh',
  'jmoyW43cSGldKIldOSkLu8kDr8omWRO=',
  'WOK6dsvJWPddMCkeW5HTW53dO8kCiCk/mmo8WQiGW7fWzmkNW7e=',
  'WPJcT01Z',
  'WOK+dYHHWPFdImkfW44=',
  'WOj0WOqrcW==',
  'vf1cd8kD',
  'aSolW75PW6C=',
  'W6SsW6hcG8k8v8oF',
  'WPJcMb8faG==',
  'yqpdNmoYna==',
  'AbaiACom',
  'WP8kW788W5m=',
  'WOCiW7mIoCoH',
  'W4hdNqXAtqldOIFcPZGuW43dQa==',
  'W4XeWQO=',
  'c8kqWQ3cPMpcIfRcMZ3dHhldSxOFAmkRw2rV',
  'kmkrz8otWP7cUwu=',
  'WRiCW7SGp8oHW5RdJq==',
  'WOqDW51TCG==',
  'tYatha==',
  'W4zHW6uFyJNdNG==',
  'mSo0WQVdTCkUWPNcIComDCoGECoRW7ddMaC=',
  'WQvPW6z9',
  'aSoYkSopW77cMey=',
  'WQZdNSoPe8oVW6FcGq==',
  'W7WZCCodWOuDW5m=',
  'W4VcSCojWR3cRa==',
  'sCoxWP0bsH3dTCoTWOy=',
  'sSogW6f8WPG=',
  'W7eFW7FcG8kHDG==',
  'WPm2WRj8emk3uq==',
  'WO8LW7qNW5veWOddPmkfW5RdOW==',
  'WPddHeLAs8oeWRe=',
  'W6H9W4xdJ8k9',
  'p8kFWOxcVYb/W6tcQvu=',
  'W6aIWPlcKmo0u8ob',
  'WObwaCk1zvxcJI7dHCoDW5S=',
  'bcOsag13CCoCW5pdUSoPW7tcGZDczSobW4BcK8o9',
  'fCoiWOpdV8k3WPldN8oQW580',
  'WQhcSfjZWQm=',
  'fmo/WQldPa==',
  'jCkTAmkqW70=',
  'FHdcHXalWO1sW4Gofa==',
  'WRC0gJiX',
  'uavvW4utgSosWOHfW48=',
  'WP7cTIy+yCoI',
  'WOzStxTJ',
  'mmoEW4VcKGVdMq==',
  'W4XaWQzjWPqDn8kydZ8q',
  'W7ytW5BcKSk2CCoxWPm=',
  'WQGResr0',
  'cSoEW6PJW7BcJmkuWQhdUgLxWQNdSqpdNLa=',
  'WPulFSoGDW==',
  'WOWKW5Klp8o8W4xdSxjXW7PdhKi=',
  'W4BcLSoXc8or',
  'd8oal8kg',
  'AbypACom',
  'WRFdI8o2gW==',
  'W5u3WQXjmW==',
  'h8knCmoeWOe=',
  'gKnFemkqjSkaWO0AWOuPWO0rlG==',
  'aNTuFZa=',
  'WPZcSxvIWR1JWRf0',
  'WOeDW7n7',
  'W6SttCkUWPNcRISBaxddIq==',
  'cCkeWPlcOGX9',
  'WQGWWRS=',
  'iSoUWQFdSSk/WOu=',
  'WPRdI0fty8oJWRBcLLhcRfO=',
  'W6ODW7BcQCkZDSoPWOyoqCooWO/cHNq=',
  'W7GzDCkeWPBcVZW2e2RdGYm=',
  'W4voWQaGWPWeCCkawmk4',
  'WO3cMmk1W7NdNhDkCfa=',
  'W5ruWQa9WPy8ASkj',
  'WO3cNmk1W6pdJNDvDW==',
  'aSo6WQJdSSk+WPNcMSkOwmoXy8oXW6BdKWe=',
  'lSkjWO7cPar8',
  'WOtcMGC=',
  'qurNeSklBmkgWQelW5GK',
  'W7/dHX0osa==',
  'W5zDWReLWPeWFq==',
  'WR/cICkQrCk/',
  'WQlcR8kKW7/dIxztDu4plG==',
  'WPZdGCoMWQ3cMa==',
  'WPOmW4vNBG==',
  'rmklW4nova==',
  'xmkxWRSIWO9BW6NcG8oD',
  'W61UmSkEW5W=',
  'adegdvldRG==',
  'bCkyWOJcQbm=',
  'W73dQ8kEW6pdSSoNWRG=',
  'ACoABvTb',
  'dCkuWQL7',
  'WQWkrLhdK1Pdt8oCrSkRW4f2W60=',
  'rrLzW5mFcCos',
  'bZGHgwxdICk3CmkyBmoLaJ3cQZS=',
  'ad0gh14=',
  'tbjuW4yseq==',
  'W4ukW7T5',
  'WP0PBNZdN2fv',
  'tYezfSkZ',
  'WPXnimk2',
  'WPKVWP7cVq==',
  'WONdRXaSWQO=',
  'WRvCWQz5',
  'WR8kW78G',
  'WQ7cLCkLW6ldJxztB04=',
  'W60JWPxcGmoHECojWQ0=',
  'gdS7hLtdR8klra==',
  'WOa6dqrQWPpdKCkpW5j8W63cTCk9ma==',
  'WOvmkmkOAW==',
  'WOzMq3a=',
  'vNLgWOqcsZS=',
  'EmktWRq1WOHCW7JdHSoTwSoWfmownIC=',
  'w0C2pq==',
  'W47dRCktW7ldSmo1WQxdGq==',
  'eatdJHTAw34=',
  'W4LOWQ1Wxq==',
  'W6StuSk1WPZcOJC/',
  'quymWPTx',
  'W7OsyG==',
  'W7W6DSojWOuaW5pcKSoTW5hdUa==',
  'eSozWPtdTmk2WPe=',
  'WReJBxW=',
  'W4LLWQaV',
  'd8onl8kg',
  'yevGAmkFWQWOW6JcTCkOvmo6W47dLCo5WRhcOaW=',
  'WRKMAq==',
  'naVdIq==',
  'tCkAW5LExHldUmoY',
  'qfiNnCkvvmkI',
  'dmkEWO/cOef7W67cQeRcICoLW7OWDq==',
  'iSosWPtdVSk+WPO=',
  'WPDVW57dOSoma8oiuCoL',
  'WPr8WPWDdsRdNMm=',
  'WO7cGmk4W77dNa==',
  'dY4iiNrZE8oC',
  'ds4lia==',
  'W5maC8obWO4xW5lcKSo0W5RdUCk1kNVdHCoblmompmoSWPu=',
  'W6u2omoSsL7cNSot',
  'WONdRryS',
  'iSkdWPpcUq==',
  'imouWOldO8k8WPBdKG==',
  'WPq8cYrJWPG=',
  'amouWOldO8k8WPBdKG==',
  'lmooW5RcHXS=',
  'WOuiW4fOz3FcHa==',
  'WObwhSkUyfNcKGO=',
  'cIecihLDEG==',
  'gmovW7zLW6VcS8kg',
  'yqpdNSoYnq==',
  'W78VAmonWPG=',
  'WPJcNHKfvG==',
  'WPxdHu5Er8oIWRJcLG==',
  'yCkfoWqiWOlcLG==',
  'W4jzWQ06WPu=',
  'W6WmBCkOWPO=',
  'eJOdn3G=',
  'gfVcMKqt',
  'lCoucW==',
  'W63cHuvDwq==',
  'WPaXW55cgG==',
  'nW8Gc0JdOSkjrSk4vmoj',
  'DrRcLa==',
  'ECkEoHmj',
  'W64PWOlcSmoGECokWRXUWPSkWPWTWRu=',
  'WOjNWPODgIO=',
  'W4ujW7LZWPu=',
  'w2NcVSkPDYfbW4hdUKG=',
  'tvpcIq==',
  'WQ7cLXC=',
  'hZCAd0pdQa==',
  'cGxdHXS=',
  'WPNcN8k3W6ldHx1jBMycoftdP8kzWPS=',
  'mCoOpCoyW5NcKfVcPHS=',
  'WO8Rfc0=',
  'W4LRWQPWca==',
  'WP/cScq3zCoVWRK=',
  'W4BcLmoXc8or',
  'FrRcKcyjWOziW5K=',
  's2LcWO0ryaRdJCoV',
  'pSopW7PLW6e=',
  'qL48pa==',
  'W5GQW7Cvs8ktte4u',
  'ncyiiw5LBW==',
  'rhXaqG==',
  'W7/dGrao',
  'W7GWv8oqWP4AW47cNa==',
  'WPTOW4xdTa==',
  'WP/dLCo9dCoHW63cGmoDW5ZcLSoRtMWSW7S=',
  'WOhcTdO8CCoTWRT7',
  'bt0llg8=',
  'W63cGeThwwm=',
  'WQf3amkBqxVcUsNdU8o8W7TtWRTXrqhdTCoSW4eWsmkfWQ4=',
  'sGr8W5eLc8oFWQTeW4lcUxFcLa==',
  'zf3cICk9AcnkW4e=',
  'W5uXWQXjmG==',
  'W7FcM01rvv7cQG==',
  'C0FcImk7Ctq=',
  'WPSaWQT9hCkKumofWORdNCo9vvhdLSkEeSkFgb/cHG==',
  'WRvDWQj5',
  'cIegcvldR8kktCoQFCo7jcZcQIBcKLFcV8kiWQhcHYPpfCoDW6GmW759lsKrWOj8WPBcVH0=',
  'd8omlCkm',
  'omkjWPdcOqb7W6q=',
  'WRjqp8k/Df/cHa==',
  'amkiW5/cQW==',
  'm8kQWQRcGNVcMuBcMYRdNfNdSq==',
  'W7bUuCkO',
  'q0iYk8kn',
  'W5KOW784qq==',
  'W61UpCkEW5W=',
  'W7G5WPpcH8o1',
  'W5y8WP7cLmoIAmoiWRq=',
  'W4VcS8oeWR3cRq==',
  'C8k/WPuoWOLgW6/cTmokwCoQbSowjW==',
  'emkkWQy6WQi=',
  'wurm',
  'WOzQq3a=',
  'W7NdO8kDW7tdQmo+WQZcLqOez8o1B18A',
  'W5G0W7eV',
  'yqBdNmoYya==',
  'WOTQW4BdRSok',
  'iSoRWRFdPmkQWPpcICo6B8oU',
  'wCkxW4Hjvq==',
  'iCoZWQtdR8k/WPJcKmoIAq==',
  'WRFdLCo9gSo2W4VcGG==',
  'Df3cPSkNCInwW7BdHMyy',
  'W7mtySkGWPRcOJy2',
  'W7bSwSkIxq==',
  'WPJcMb4faG==',
  'WQvQW60I',
  'zv45pCkBqmk0W4pdJSojWORcRSoJ',
  'mmo0c8oEW6RcNLdcRW==',
  'k8ozW5FdTW==',
  'x8klW4nFqWVdQSk+WPmEW70Fsq==',
  'y1RcMmkNAcmjW5ddN2eyb8k1BCoji3ldP8kp',
  'fYa1kNrGF8oC',
  'hrJdNrTas3PeW7S=',
  'WPmiW5nXyq==',
  'tSkclqqwWQlcIa==',
  'WQC+WRb0lmkLtSojWPldKCo6zW==',
  'W74LWPG=',
  'WPZdHmoTWQ3dJq==',
  'bYafmgX3CSonW7JdOSo/W5VcNW1x',
  'W6H6W4ZdHa==',
  'WRhdImo6d8o7',
  'WO3cKCkMW7BdHwS=',
  'ANrygmkqBmkAWOSFW4yEWOWsnCkNWPPVAmokWRO=',
  'W6q+D8oRWPSDW7dcICoTW4/dRSkyk2W=',
  'l8oyW5FcKbRdNW==',
  'W70JWQxcGCo+DCojWR4=',
  'W4aJz8k5WORcUtaUbxhdSZJcICorirddOuSkpW==',
  'fYa1mxn7CSoE',
  'W4vDWOe3nIxdKCkK',
  'kSotW53cKHBdUcK=',
  'W5uWWQvj',
  'WR/cJCkPrCk/',
  'r31nsCkUWQjU',
  'WPvYospdGG==',
  'yqFdK8oYya==',
  'quuaWPa=',
  'WQZdQw9nxmo8WQtcNvC=',
  'W5hcGufrxW==',
  'ACoyzva=',
  'WPHQWOWDbWVdMq==',
  'k8oFW5FdTXr2W6xcOKFcICoUW6XU',
  'WONdKSo3g8oHW7pcLW==',
  'WOmfW5rQ',
  'WO3dHx5lqCoIWRNcNW==',
  'zSkkkqGxWQZcHa8J',
  'w8kxWQSRWPrbW6ZcJ8oarSoS',
  'W4NcNeDqqMBcVW==',
  'yqpdNCoYna==',
  'f3tcL3/cJ2tcLCkJW63dPa==',
  'v2HeWOentZFdPSoA',
  'WRqfW4nRA3e=',
  'WPL2WO0E',
  'WOZdOwDHyq==',
  'W7vbW4y=',
  'WPu6cs1NWPxdMq==',
  'WQvUW6yO',
  'W4WfW7uA',
  'W4CVW7mTuCkE',
  'bxlcMN/cLW==',
  'tYeEfG==',
  'W6H+W47dJ8oP',
  'W5amzmkZWO8=',
  'bSoFWPldGCkYWO3dL8oKW4GVwmkM',
  'W7/dHXaosa==',
  'W7BcLfP7wN/cNmk3iSkquCk+pNm=',
  'W6H9W4FdJ8k9',
  'WR0hW7eMm8ohW5m=',
  'WRDrp8k1F1u=',
  'W7SPWOBcMCoTF8oc',
  'quyjWPTw',
  'WQagW4y3oCoHW5VdHa==',
  'qXH8W5mhfmodWP9zW5S=',
  'WO3cKCkGW7/dHNLkFW==',
  'WPHCi8k9zLG=',
  'zxjsWPOmqtO=',
  'W61UnCkEW5W=',
  'WPaXW55ccZBdIMO=',
  'nCo9W6VdUq==',
  'DfTBeCkz',
  'WPv2ospdGG==',
  'qmkhW4XFqbNdQSoT',
  'aNXtFW==',
  'WQRdLmokc8o8W63cISkA',
  'WPtcNSkWW7ldKfDb',
  'W4VdTmkrW67dSCoyWQ7dNc8EFa==',
  'dCkkCmoxWOZcS1HSg1mpx8kA',
  'WRBdNSoWgmoMW7a=',
  'WRD2WOCvxYpdMNVdUSonshzLCCoctc5DvMdcP2tcIhu=',
  'rvBcJCkT',
  'W51lW4y=',
  't2virCk6WQvTW4lcVCkYua==',
  'm8oyW4VcMGFdHdZdRSkKsCkS',
  'E29tWOqgrJFdTCoo',
  'WRjuWQrLomoHW5hcNG==',
  'WRKiW7y=',
  'sSobW6T8WPG=',
  'hcyhhKNdSSkCu8kV',
  'yeXEnSornSkr',
  'WPzCWOC+nW==',
  'uWDwW4Gs',
  'tmknW4b6wqJdTSoZWOicW7SEqG==',
  'x8khW49FxHxdR8o7WPe=',
  'lCotWOJdPmkR',
  'WPa1W5jj',
  'WOzQtxTJ',
  'wKnCmSoBea==',
  'd8omiSkmWP0=',
  'BSkEmqieWQtcNW4=',
  'mmkJW7/cSa==',
  'yqddN8oY',
  'W4hcJeXnxa==',
  'rCkkpa==',
  'rXjoW6qkhmolWR5EW5NcGvdcLmkaW54GWPlcSdhdKW==',
  'j8o0nSoEW73cMuRcJaahWPVdJ3FdH1e=',
  'p8kUWRFcRhW=',
  'gbZdIXDoxh1zW7lcVai=',
  'sCorWPSbwrldVCo7WOuFW7WusmoG',
  'W45zWRrzWPu0pmkfdtqkimoKW4ddPSkf',
  'W7bOxSkIxq==',
  'rvi1pCkgxSkXWOBdRa==',
  'WPVcTK9WWRS=',
  'W4vXW7abEG==',
  'W5pdImksrCogWOVcRCkr',
  'tSkzmaXqWQRcLrqtWRRdUSogWQlcLr9UhmkCowxdTbHKWRa=',
  'W4qFWR/cSa==',
  'CbVcLZyCWQXa',
  'uWnTAa==',
  'Fu1Pj8oBemkzWQu=',
  'yrLEW5mjemoc',
  'W63cGuHasa==',
  'd8oBWPddUmk0WP7dGSoMW58=',
  'W4NdImk1wmosWOVcOmkxW6JdRcu0jG==',
  'W50VW6dcISkHDSoqWOemBSoIWRNcT1jmy8kjhGtdI8kIxq==',
  'WRa2fYvPWOhdJW==',
  'hrqri8kamSouW4S=',
  'W5WYW4K+sSkztvW=',
  'W4VcSmodWR3cRa=='
];
(function(b, e) {
  var f = function(g) {
    while (--g) {
      b['push'](b['shift']());
    }
  };
  f(++e);
})(a, 302);
var b = function(c, d) {
  c = c - 0;
  var e = a[c];
  if (b['yKFdJf'] === undefined) {
    var f = function(i) {
      var j =
        'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=';
      var k = String(i)['replace'](/=+$/, '');
      var l = '';
      for (
        var m = 0, n, o, p = 0;
        (o = k['charAt'](p++));
        ~o && ((n = m % 4 ? n * 64 + o : o), m++ % 4)
          ? (l += String['fromCharCode'](255 & (n >> ((-2 * m) & 6))))
          : 0
      ) {
        o = j['indexOf'](o);
      }
      return l;
    };
    var h = function(l, m) {
      var n = [],
        o = 0,
        p,
        q = '',
        r = '';
      l = f(l);
      for (var u = 0, v = l['length']; u < v; u++) {
        r += '%' + ('00' + l['charCodeAt'](u)['toString'](16))['slice'](-2);
      }
      l = decodeURIComponent(r);
      var t;
      for (t = 0; t < 256; t++) {
        n[t] = t;
      }
      for (t = 0; t < 256; t++) {
        o = (o + n[t] + m['charCodeAt'](t % m['length'])) % 256;
        p = n[t];
        n[t] = n[o];
        n[o] = p;
      }
      t = 0;
      o = 0;
      for (var w = 0; w < l['length']; w++) {
        t = (t + 1) % 256;
        o = (o + n[t]) % 256;
        p = n[t];
        n[t] = n[o];
        n[o] = p;
        q += String['fromCharCode'](
          l['charCodeAt'](w) ^ n[(n[t] + n[o]) % 256]
        );
      }
      return q;
    };
    b['kYloqN'] = h;
    b['taAYpS'] = {};
    b['yKFdJf'] = !![];
  }
  var g = b['taAYpS'][c];
  if (g === undefined) {
    if (b['brYVpV'] === undefined) {
      b['brYVpV'] = !![];
    }
    e = b['kYloqN'](e, d);
    b['taAYpS'][c] = e;
  } else {
    e = g;
  }
  return e;
};
/* End copied string deobfuscation functions */

/*
Replace b calls
*/
refactor.replaceRecursive(
  `CallExpression[callee.type="IdentifierExpression"][callee.name="` + deobfuscationFunctionName + `"][arguments.length=2][arguments.0.type="LiteralStringExpression"][arguments.1.type="LiteralStringExpression"]`,

  node => {
    return new Shift.LiteralStringExpression({
      value: b(node.arguments[0].value, node.arguments[1].value)
    })
  }
);
console.log("/* Replaced b deobfuscation calls */")

console.log("/* This file is the result of running `node giveaway_spam_deobfuscator.js > giveaway_spam_deobfuscated.js` */");
refactor.expandBoolean();
refactor.convertComputedToStatic();
console.log(refactor.print());
